apiVersion: apps/v1 # precisa ser assim, está dentro do apps
kind: Deployment
metadata:
  name: app-venda-deploy
spec:
  replicas: 1
  selector:
    # labels que o deployment vai ler
    matchLabels:      
      app: venda-app 
  # são anotações do pod que o deployment vai gerenciar
  template:
    metadata:
      name: venda-app-pod
      labels:
        app: venda-app
    spec:
      containers:
      - name: venda-app-image
        image: teteo/venda-app:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:    
        - name: MYSQL_HOST
          value: mysql-service-2
        - name: MYSQL_DB_NAME
          value: dbInfnet
        - name: MYSQL_USER
          value: root   
        - name: MYSQL_PASSWORD
          value: teteo
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10