apiVersion: v1
kind: Service
metadata:
  name: app-venda-service-2
spec:
  # vai criar uma porta do localhost para um pod
  type: NodePort
  selector:
    # o serviço vai ligar com todos os pods que tem essa label
    app: venda-app
  ports:
  - protocol: TCP
    targetPort: 8081
    port: 8081    
    nodePort: 30020