apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmeter-pvc
spec:
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
    